version: '3'

services:
  api:
    build: ./server
    ports:
      - 8000:8000
    restart: unless-stopped
  client:
    build: ./client
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - "api"