version: '3'

services:
  scoir-login-server:
    build: ./server
    ports: 
      - ${API_PORT}:${API_PORT}
    restart: unless-stopped
    networks:
      - api
  scoir-login-client:
    build: ./client
    ports:
      - 3000:3000
    restart: unless-stopped
    depends_on:
      - scoir-login-server
    environment:
      - REACT_APP_BASE_API_URL=${API_URL}
      - REACT_APP_BASE_API_PORT=${API_PORT}

networks:
  api: